// A "lens" is a subject seen through the story. Each step is tagged with the
// lenses it teaches, so one history track also teaches medicine, economics, etc.
export type Lens =
  | 'history'
  | 'medicine'
  | 'economics'
  | 'geography'
  | 'philosophy'
  | 'politics'
  | 'religion'
  | 'science'

export const LENS_LABELS: Record<Lens, string> = {
  history: 'History',
  medicine: 'Medicine',
  economics: 'Economics',
  geography: 'Geography',
  philosophy: 'Philosophy',
  politics: 'Politics',
  religion: 'Religion',
  science: 'Science',
}

export type StoryStep = {
  type: 'story'
  title?: string
  body: string[]
  lenses?: Lens[]
}

export type ChoiceStep = {
  type: 'choice'
  prompt: string
  options: string[]
  answer: number
  explain: string
  lenses?: Lens[]
}

/** Items are listed in their correct order; the player shuffles them. */
export type OrderStep = {
  type: 'order'
  prompt: string
  items: string[]
  explain: string
  lenses?: Lens[]
}

export type MatchStep = {
  type: 'match'
  prompt: string
  categories: string[]
  items: { text: string; category: string }[]
  explain: string
  lenses?: Lens[]
}

export type EstimateStep = {
  type: 'estimate'
  prompt: string
  min: number
  max: number
  step: number
  unit: string
  answer: number
  tolerance: number
  explain: string
  lenses?: Lens[]
}

/** Track or lesson opener: where and when we are, and why it matters. */
export type OrientStep = {
  type: 'orient'
  title: string
  /** Years; negative = BCE. */
  from: number
  to: number
  /** Key places; the first is highlighted. */
  places: { name: string; lon: number; lat: number; label?: 'left' | 'right' }[]
  /** One line explaining what the map shows. */
  placesNote?: string
  mapBounds?: { west: number; south: number; east: number; north: number }
  why: string
  /** Short scene-setting facts: the world at that moment. */
  context: string[]
  lenses?: Lens[]
}

/** Introduces one new term in plain language before it's used. */
export type ExplainStep = {
  type: 'explain'
  term: string
  plain: string
  analogy: string
  why?: string
  lenses?: Lens[]
}

/** A no-penalty guess before the reveal — builds curiosity and the generation effect. */
export type PredictStep = {
  type: 'predict'
  prompt: string
  options: string[]
  answer: number
  reveal: string
  lenses?: Lens[]
}

/** Place an event on a stretch of the timeline, next to anchors the learner already knows. */
export type TimelineStep = {
  type: 'timeline'
  prompt: string
  event: string
  year: number
  min: number
  max: number
  tolerance: number
  anchors: { year: number; label: string }[]
  explain: string
  lenses?: Lens[]
}

/** Side-by-side comparison. Cells in `blanks` are hidden and filled from a shuffled pool. */
export type CompareStep = {
  type: 'compare'
  prompt: string
  columns: string[]
  rows: { label: string; cells: string[] }[]
  blanks: [row: number, col: number][]
  explain: string
  lenses?: Lens[]
}

/** Feynman recap: explain the lesson's question in your own words, then check against key points. */
export type RecapStep = {
  type: 'recap'
  prompt: string
  keyPoints: string[]
  model: string
}

/** Generated by the lesson player from the lesson's cards; not written by authors. */
export type CardStep = { type: 'card'; card: Card; lenses?: Lens[] }

export type WidgetId = 'plague-map' | 'labor-market'

export type InteractiveStep = {
  type: 'interactive'
  widget: WidgetId
  title: string
  prompt: string
  takeaway: string
  lenses?: Lens[]
}

export type Step =
  | StoryStep
  | ChoiceStep
  | OrderStep
  | MatchStep
  | EstimateStep
  | InteractiveStep
  | OrientStep
  | ExplainStep
  | PredictStep
  | TimelineStep
  | CompareStep
  | RecapStep
  | CardStep

/**
 * A memory card reviewed on a spaced schedule after its lesson is done.
 * With `choices` (wrong options) it is answered by picking; without, it is
 * flipped and self-graded.
 */
export type Card = {
  /** Stable id — never reuse or rename, or learners lose their review history. */
  id: string
  kind: 'date' | 'number' | 'person' | 'place' | 'concept' | 'compare' | 'cause'
  front: string
  back: string
  choices?: string[]
  /** For date cards: the year (negative = BCE), so it can be pinned on the learner's timeline. */
  year?: number
  /** Optional memory hook shown after answering (mnemonic, anchor, image). */
  hook?: string
}

export type Lesson = {
  id: string
  title: string
  summary: string
  /** The central question the lesson answers — shown up front and in the recap. */
  question?: string
  /** One-line "previously…" recap shown on the lesson's opening screen. */
  previously?: string
  steps: Step[]
  /** Memory cards: quizzed at the end of the lesson, then reviewed on a spaced schedule. */
  cards?: Card[]
  /** Cliffhanger shown on the finish screen, pointing to the next lesson. */
  teaser?: string
}

export type Track = {
  id: string
  /** Tracks in the same series are levels of one topic; level N+1 continues level N. */
  series: string
  tier: number
  title: string
  tagline: string
  lenses: Lens[]
  /** Years the story covers (negative = BCE); used to sort and label tracks. */
  era: [from: number, to: number]
  /** Costs no key — the orientation track everyone should take first. */
  free?: boolean
  /** Continues this track instead of the previous tier of the same series. */
  after?: string
  /** Empty for tracks whose content isn't written yet. */
  lessons: Lesson[]
}

export type TestQuestion = {
  prompt: string
  options: string[]
  answer: number
}

/** Steps that are graded and count toward first-try XP. Predictions are guesses, never graded. */
export const isQuestion = (s: Step): boolean =>
  s.type === 'choice' ||
  s.type === 'order' ||
  s.type === 'match' ||
  s.type === 'estimate' ||
  s.type === 'timeline' ||
  s.type === 'compare' ||
  s.type === 'card'
